#!/usr/bin/env bash

# Root check
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Fetch absolute path to this script
INFRABACKUP_INSTALLATION_DIRECTORY=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

source "${INFRABACKUP_INSTALLATION_DIRECTORY}/includes/output.inc.sh"
source "${INFRABACKUP_INSTALLATION_DIRECTORY}/includes/config.inc.sh"
source "${INFRABACKUP_INSTALLATION_DIRECTORY}/includes/rsync.inc.sh"
source "${INFRABACKUP_INSTALLATION_DIRECTORY}/includes/rdiff.inc.sh"
source "${INFRABACKUP_INSTALLATION_DIRECTORY}/includes/hooks.inc.sh"
source "${INFRABACKUP_INSTALLATION_DIRECTORY}/includes/cron.inc.sh"
source "${INFRABACKUP_INSTALLATION_DIRECTORY}/commands/fiddle.sh"
source "${INFRABACKUP_INSTALLATION_DIRECTORY}/commands/help.sh"
source "${INFRABACKUP_INSTALLATION_DIRECTORY}/commands/show.sh"
source "${INFRABACKUP_INSTALLATION_DIRECTORY}/commands/backup.sh"
source "${INFRABACKUP_INSTALLATION_DIRECTORY}/commands/cron.sh"

case $1 in

help)
  help
  exit 0
  ;;
show)
  show
  exit 0
  ;;
cron)
  cron $2 $3 $4
  exit $?
  ;;
fiddle)
  fiddle $2 $3 $4
  exit $?
  ;;
backup)
  backup $2
  exit $?
  ;;
new)
  new
  exit $?
  ;;
*)
  help
  exit $?
  ;;
esac
