#!/usr/bin/env bash

declare -A CONFIG

# Cron
CONFIG[cron]="* * * * *"

# Host
CONFIG[host]="your-target-server"

# Rsync
CONFIG[rsync_args]="-arv --inplace --delete --stats"
CONFIG[rsync_target]="/path/to/your/backups/rsync/"

# Rdiff
CONFIG[rdiff_args]="-v5 --print-statistics --exclude-device-files --exclude-fifos --exclude-sockets --preserve-numerical-ids --exclude-other-filesystems"
CONFIG[rdiff_target]="/path/to/your/backups/rsync/"

# Mail
CONFIG[mail_to]=""

# Log
CONFIG[log_directory]="/path/to/your/backups/logs/"
